name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            package_tarball: true
          - os: macos-latest
            package_tarball: false
          - os: windows-latest
            package_tarball: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - if: matrix.package_tarball
        run: yarn package:tarball
      - run: yarn package:binaries
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/releases/*.tar.gz
            dist/releases/*.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
